/*
 * EWO-014.14A Backfill — Canonical Completion Reports for Existing PO-Accepted EWOs
 */

DO $$
DECLARE
  v_ewo RECORD;
  v_report_body text;
  v_report_id uuid;
  v_existing uuid;
  v_lifecycle_summary text;
  v_event RECORD;
  v_backfilled int := 0;
  v_skipped int := 0;
BEGIN
  FOR v_ewo IN
    SELECT * FROM engineering_work_orders
    WHERE status = 'closed'
      AND closure_method = 'Product Owner Acceptance'
  LOOP
    SELECT id INTO v_existing
    FROM ewo_completion_reports
    WHERE ewo_id = v_ewo.id
    ORDER BY generated_at DESC LIMIT 1;

    IF v_existing IS NOT NULL THEN
      v_skipped := v_skipped + 1;
      CONTINUE;
    END IF;

    v_lifecycle_summary := '';
    FOR v_event IN
      SELECT * FROM ewo_lifecycle_events
      WHERE ewo_id = v_ewo.id ORDER BY created_at ASC
    LOOP
      v_lifecycle_summary := v_lifecycle_summary ||
        '  ' || to_char(v_event.created_at, 'DD Mon YYYY HH24:MI') ||
        ' — ' || COALESCE(v_event.from_status, '—') || ' → ' || v_event.to_status ||
        ' (' || COALESCE(v_event.actor, 'system') || ')' || E'\n';
    END LOOP;

    v_report_body := array_to_string(ARRAY[
      'ENGINEERING COMPLETION REPORT (Governed Retrospective Backfill)',
      'Work Order: ' || v_ewo.ewo_ref,
      'Title: ' || v_ewo.title,
      'Generated: ' || to_char(now(), 'DD Mon YYYY HH24:MI:SS'),
      'Backfill: This report was generated retrospectively by governed backfill.',
      '',
      'EXECUTIVE SUMMARY',
      COALESCE(v_ewo.executive_summary, 'No executive summary available. Generated by governed retrospective backfill using available EWO data.'),
      '',
      'SCOPE COMPLETED',
      COALESCE(v_ewo.scope, 'No scope documented. Source scope artefact was unavailable at time of backfill.'),
      '',
      'LIFECYCLE SUMMARY',
      COALESCE(NULLIF(v_lifecycle_summary, ''), 'No lifecycle events recorded. Lifecycle event history was unavailable at time of backfill.'),
      '',
      'VALIDATION RESULTS',
      COALESCE(v_ewo.validation_notes, 'No validation notes recorded. Validation evidence was unavailable at time of backfill.'),
      '',
      'BUILD RESULT',
      'Build result not available in retrospective backfill. Implementation evidence was not captured in the EWO record.',
      '',
      'RISKS',
      CASE WHEN v_ewo.risk_level IS NOT NULL AND v_ewo.risk_level != 'low'
        THEN 'Risk level: ' || upper(v_ewo.risk_level) || '. Risk assessment details unavailable in retrospective backfill.'
        ELSE 'No significant risks identified.' END,
      '',
      'PRODUCT OWNER DECISIONS',
      COALESCE(v_ewo.po_acceptance_notes, 'No specific Product Owner decisions recorded.'),
      '',
      'ENGINEERING ACCEPTANCE RECOMMENDATION',
      'Recommended for Product Owner Acceptance. (Retrospectively confirmed — EWO was already closed via PO Acceptance.)',
      '',
      'CLOSURE',
      'Method: ' || COALESCE(v_ewo.closure_method, 'Product Owner Acceptance'),
      'Closed by: ' || COALESCE(v_ewo.closed_by, 'Unknown'),
      'Closed at: ' || COALESCE(to_char(v_ewo.closed_at, 'DD Mon YYYY HH24:MI'), 'Unknown'),
      CASE WHEN v_ewo.po_accepted_by IS NOT NULL THEN 'Accepted by: ' || v_ewo.po_accepted_by ELSE '' END,
      CASE WHEN v_ewo.po_accepted_at IS NOT NULL THEN 'Accepted at: ' || to_char(v_ewo.po_accepted_at, 'DD Mon YYYY HH24:MI') ELSE '' END,
      '',
      'LLND Automate - Engineering Execution Engine',
      'Generated by Governed Retrospective Backfill'
    ], E'\n');

    INSERT INTO ewo_completion_reports (
      ewo_id, ewo_ref, title, executive_summary, scope_completed,
      lifecycle_summary, validation_results, build_result, risks,
      po_decisions, acceptance_recommendation, report_body, generated_at,
      accepted_at, accepted_by
    ) VALUES (
      v_ewo.id, v_ewo.ewo_ref,
      'Completion Report (Backfill) — ' || v_ewo.title,
      COALESCE(v_ewo.executive_summary, 'Generated by governed retrospective backfill. Executive summary was unavailable in the EWO record.'),
      COALESCE(v_ewo.scope, 'Scope artefact unavailable at time of backfill.'),
      COALESCE(NULLIF(v_lifecycle_summary, ''), 'Lifecycle events unavailable at time of backfill.'),
      COALESCE(v_ewo.validation_notes, 'Validation evidence unavailable at time of backfill.'),
      'Build result not available in retrospective backfill.',
      CASE WHEN v_ewo.risk_level != 'low' THEN 'Risk level: ' || upper(v_ewo.risk_level) || '. Details unavailable.' ELSE 'No significant risks identified.' END,
      COALESCE(v_ewo.po_acceptance_notes, 'No PO decisions recorded.'),
      'Recommended for Product Owner Acceptance. (Retrospectively confirmed.)',
      v_report_body, now(),
      COALESCE(v_ewo.po_accepted_at, now()), COALESCE(v_ewo.po_accepted_by, v_ewo.closed_by)
    ) RETURNING id INTO v_report_id;

    UPDATE engineering_work_orders
    SET report_generation_status = 'available'
    WHERE id = v_ewo.id;

    INSERT INTO ewo_lifecycle_events (ewo_id, from_status, to_status, actor, notes)
    VALUES (
      v_ewo.id, v_ewo.status, v_ewo.status, 'system',
      'Governed Retrospective Backfill: Canonical Engineering Completion Report generated. '
      'Report ID: ' || v_report_id::text || '. '
      'This report was generated retrospectively for an EWO already closed via Product Owner Acceptance. '
      'Some implementation evidence may be unavailable.'
    );

    v_backfilled := v_backfilled + 1;
  END LOOP;

  RAISE NOTICE 'Backfill complete: % reports generated, % skipped (already existed)', v_backfilled, v_skipped;
END;
$$;