/*
# Conversation Lifecycle Automation — Phase X

## Summary
Extends the AI Technical Director conversation system with intelligent automation:
auto-completion tracking, historical migration metadata, artefact linking,
and a permanent conversation health review store.

## Changes

### Modified Tables

**cc_ai_conversations**
- `auto_completed` (boolean, default false) — true when system completed the conversation (not the user)
- `completion_reason` (text, nullable) — machine-readable reason: 'engineering_work_complete' | 'historical_migration' | 'orphaned' | 'manual'
- `migration_notes` (text, nullable) — notes recorded during historical review pass

### New Tables

**ecc_conversation_health_reviews**
Permanent store for conversation health review reports generated by the
analyze-conversations function. Each run produces one immutable record.
- `id` (uuid, primary key)
- `run_at` (timestamptz) — when the analysis ran
- `total_analysed` (integer) — total conversations reviewed
- `auto_completed` (integer) — conversations auto-completed this run
- `remaining_active` (integer) — conversations left active after review
- `flagged_for_review` (integer) — conversations flagged for PO attention
- `orphaned` (integer) — conversations with no engineering artefact links
- `unclear_titles` (integer) — conversations with generic/unclear titles
- `duplicate_pairs` (integer) — duplicate conversation groups detected
- `summary` (text) — narrative summary of the review
- `recommendations` (jsonb) — array of recommendation objects
- `conversation_details` (jsonb) — per-conversation analysis results
- `created_at` (timestamptz)

**ecc_conversation_artefact_links**
Explicit links between conversations and engineering artefacts of any type.
Extends the existing ecc_ai_artefact_log (which is append-only and creation-focused)
with a broader linking table that supports linking to artefacts not created by AI.
- `id` (uuid, primary key)
- `conversation_id` (uuid, FK to cc_ai_conversations)
- `artefact_type` (text) — audit | feature | release | test_plan | decision | documentation | epic | goal | backlog_item | guardian_review | change_record
- `artefact_id` (uuid, nullable) — FK to the target record
- `artefact_ref` (text, nullable) — human-readable ref (e.g. AUD-001, RC-003)
- `artefact_title` (text, nullable) — title snapshot at time of linking
- `link_confidence` (numeric 2dp, 0-100) — confidence this link is correct
- `link_source` (text) — 'ai_analysis' | 'manual' | 'historical_migration'
- `notes` (text, nullable)
- `linked_at` (timestamptz, default now())

## Security
- Both new tables use RLS with TO anon, authenticated (single-tenant app, no sign-in requirement).
- Existing cc_ai_conversations columns added with safe defaults; no data migration needed.
*/

-- ─── Extend cc_ai_conversations ──────────────────────────────────────────────

ALTER TABLE cc_ai_conversations
  ADD COLUMN IF NOT EXISTS auto_completed     boolean     NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS completion_reason  text,
  ADD COLUMN IF NOT EXISTS migration_notes    text;

CREATE INDEX IF NOT EXISTS idx_cc_ai_conversations_auto_completed
  ON cc_ai_conversations (auto_completed) WHERE auto_completed = true;

-- ─── Conversation Health Reviews ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ecc_conversation_health_reviews (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_at               timestamptz NOT NULL DEFAULT now(),
  total_analysed       integer     NOT NULL DEFAULT 0,
  auto_completed_count integer     NOT NULL DEFAULT 0,
  remaining_active     integer     NOT NULL DEFAULT 0,
  flagged_for_review   integer     NOT NULL DEFAULT 0,
  orphaned             integer     NOT NULL DEFAULT 0,
  unclear_titles       integer     NOT NULL DEFAULT 0,
  duplicate_pairs      integer     NOT NULL DEFAULT 0,
  summary              text,
  recommendations      jsonb       NOT NULL DEFAULT '[]'::jsonb,
  conversation_details jsonb       NOT NULL DEFAULT '[]'::jsonb,
  created_at           timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE ecc_conversation_health_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_health_reviews" ON ecc_conversation_health_reviews;
CREATE POLICY "anon_select_health_reviews" ON ecc_conversation_health_reviews FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_health_reviews" ON ecc_conversation_health_reviews;
CREATE POLICY "anon_insert_health_reviews" ON ecc_conversation_health_reviews FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_health_reviews" ON ecc_conversation_health_reviews;
CREATE POLICY "anon_update_health_reviews" ON ecc_conversation_health_reviews FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_health_reviews" ON ecc_conversation_health_reviews;
CREATE POLICY "anon_delete_health_reviews" ON ecc_conversation_health_reviews FOR DELETE
  TO anon, authenticated USING (true);

-- ─── Conversation Artefact Links ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ecc_conversation_artefact_links (
  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id  uuid        NOT NULL REFERENCES cc_ai_conversations(id) ON DELETE CASCADE,
  artefact_type    text        NOT NULL,
  artefact_id      uuid,
  artefact_ref     text,
  artefact_title   text,
  link_confidence  numeric(5,2) NOT NULL DEFAULT 100,
  link_source      text        NOT NULL DEFAULT 'manual',
  notes            text,
  linked_at        timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE ecc_conversation_artefact_links ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_conv_artefact_links" ON ecc_conversation_artefact_links;
CREATE POLICY "anon_select_conv_artefact_links" ON ecc_conversation_artefact_links FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_conv_artefact_links" ON ecc_conversation_artefact_links;
CREATE POLICY "anon_insert_conv_artefact_links" ON ecc_conversation_artefact_links FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_conv_artefact_links" ON ecc_conversation_artefact_links;
CREATE POLICY "anon_update_conv_artefact_links" ON ecc_conversation_artefact_links FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_conv_artefact_links" ON ecc_conversation_artefact_links;
CREATE POLICY "anon_delete_conv_artefact_links" ON ecc_conversation_artefact_links FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_conv_artefact_links_conv
  ON ecc_conversation_artefact_links (conversation_id);
CREATE INDEX IF NOT EXISTS idx_conv_artefact_links_type_id
  ON ecc_conversation_artefact_links (artefact_type, artefact_id);
