/*
# TP-001 Seed — Test Plan, 34 Suites, 102 Test Cases

## Purpose
Seeds the permanent TP-001 Platform Release Validation Suite into the existing
test management tables (ecc_test_plans, ecc_test_suites, ecc_test_cases).

## What is seeded

### 1 Test Plan: TP-001
- "Platform Release Validation Suite"
- type: release_validation, priority: critical

### 34 Test Suites (TS-001 through TS-034)
One suite per major platform domain:
Authentication, Mission Control, CEO Dashboard, AI Technical Director,
Engineering Guardian, Engineering Documentation, Engineering Change Log,
Product Audit, Engineering Programme, Goals & Epics, Roadmap,
Ideas & Backlog, Features, Releases, Testing Framework, Engineering Audits,
Documentation, Knowledge Centre, Settings, AI Providers, Navigation, Search,
Reporting, Shared Data Layer, Database, Supabase Edge Functions, Integrations,
Performance, Security, Accessibility, Responsive Layout, Mission Control Layout,
Scroll Container Validation, Error Handling

### 102 Test Cases (TP001-TC-001 through TP001-TC-102)
3 test cases per suite, covering critical validation scenarios for each domain.

## Notes
- Idempotent: skips seed if TP-001 plan already exists
- Cases use severity field for priority (critical/high/medium/low)
- All cases start with status = 'pending', test_type = 'manual'
*/

DO $$
DECLARE
  p_id uuid;
  s01 uuid; s02 uuid; s03 uuid; s04 uuid; s05 uuid;
  s06 uuid; s07 uuid; s08 uuid; s09 uuid; s10 uuid;
  s11 uuid; s12 uuid; s13 uuid; s14 uuid; s15 uuid;
  s16 uuid; s17 uuid; s18 uuid; s19 uuid; s20 uuid;
  s21 uuid; s22 uuid; s23 uuid; s24 uuid; s25 uuid;
  s26 uuid; s27 uuid; s28 uuid; s29 uuid; s30 uuid;
  s31 uuid; s32 uuid; s33 uuid; s34 uuid;
BEGIN

IF EXISTS (SELECT 1 FROM ecc_test_plans WHERE plan_number = 'TP-001') THEN RETURN; END IF;

p_id := gen_random_uuid();
s01  := gen_random_uuid(); s02 := gen_random_uuid(); s03 := gen_random_uuid();
s04  := gen_random_uuid(); s05 := gen_random_uuid(); s06 := gen_random_uuid();
s07  := gen_random_uuid(); s08 := gen_random_uuid(); s09 := gen_random_uuid();
s10  := gen_random_uuid(); s11 := gen_random_uuid(); s12 := gen_random_uuid();
s13  := gen_random_uuid(); s14 := gen_random_uuid(); s15 := gen_random_uuid();
s16  := gen_random_uuid(); s17 := gen_random_uuid(); s18 := gen_random_uuid();
s19  := gen_random_uuid(); s20 := gen_random_uuid(); s21 := gen_random_uuid();
s22  := gen_random_uuid(); s23 := gen_random_uuid(); s24 := gen_random_uuid();
s25  := gen_random_uuid(); s26 := gen_random_uuid(); s27 := gen_random_uuid();
s28  := gen_random_uuid(); s29 := gen_random_uuid(); s30 := gen_random_uuid();
s31  := gen_random_uuid(); s32 := gen_random_uuid(); s33 := gen_random_uuid();
s34  := gen_random_uuid();

INSERT INTO ecc_test_plans (id, plan_number, title, description, status, test_type, priority, total_suites, total_cases)
VALUES (p_id, 'TP-001', 'Platform Release Validation Suite',
  'Mandatory validation suite executed before every release. Covers all 34 platform domains with 102 test cases.',
  'active', 'release_validation', 'critical', 34, 102);

INSERT INTO ecc_test_suites (id, plan_id, suite_number, title, description, category, status, total_cases) VALUES
  (s01,p_id,'TS-001','Authentication','Login, OTP, session persistence.','security','active',3),
  (s02,p_id,'TS-002','Mission Control','Dashboard load, widgets, navigation.','functional','active',3),
  (s03,p_id,'TS-003','CEO Dashboard','Metrics display, data accuracy.','functional','active',3),
  (s04,p_id,'TS-004','AI Technical Director','Query handling, context accuracy.','ai','active',3),
  (s05,p_id,'TS-005','Engineering Guardian','Review submission, detail, approval.','engineering','active',3),
  (s06,p_id,'TS-006','Engineering Documentation','Doc load, create, link.','engineering','active',3),
  (s07,p_id,'TS-007','Engineering Change Log','History display, create, filter.','engineering','active',3),
  (s08,p_id,'TS-008','Product Audit','Feature health, guardian widget, TP-001 widget.','functional','active',3),
  (s09,p_id,'TS-009','Engineering Programme','Phase display, RC link, EOS stages.','engineering','active',3),
  (s10,p_id,'TS-010','Goals & Epics','Hierarchy load, create goal, epic links.','functional','active',3),
  (s11,p_id,'TS-011','Roadmap','Item display, filtering, release links.','functional','active',3),
  (s12,p_id,'TS-012','Ideas & Backlog','Load, create, filter items.','functional','active',3),
  (s13,p_id,'TS-013','Features','Registry load, detail panel, lifecycle update.','functional','active',3),
  (s14,p_id,'TS-014','Releases','Active RC, release gate, checklist.','functional','active',3),
  (s15,p_id,'TS-015','Testing Framework','Dashboard, TP-001 access, case currency.','engineering','active',3),
  (s16,p_id,'TS-016','Engineering Audits','Audit list, detail, approval workflow.','engineering','active',3),
  (s17,p_id,'TS-017','Documentation','Doc section, ADRs, release notes.','engineering','active',3),
  (s18,p_id,'TS-018','Knowledge Centre','Accessibility, standards, decision log.','functional','active',3),
  (s19,p_id,'TS-019','Settings','Load, environment setting, OTP config.','functional','active',3),
  (s20,p_id,'TS-020','AI Providers','Default provider, health check, usage log.','ai','active',3),
  (s21,p_id,'TS-021','Navigation','All nav items resolve, mobile nav, active state.','ui','active',3),
  (s22,p_id,'TS-022','Search','Results relevance, navigation, empty state.','ui','active',3),
  (s23,p_id,'TS-023','Reporting','Guardian report copy, TP-001 report, audit sections.','functional','active',3),
  (s24,p_id,'TS-024','Shared Data Layer','Active RC consistency, shared client, usage log.','engineering','active',3),
  (s25,p_id,'TS-025','Database','Tables exist, RLS access, referential integrity.','infrastructure','active',3),
  (s26,p_id,'TS-026','Supabase Edge Functions','Guardian fn, health fn, CORS headers.','infrastructure','active',3),
  (s27,p_id,'TS-027','Integrations','aXcelerate status, email, Stripe.','integration','active',3),
  (s28,p_id,'TS-028','Performance','Mission Control load time, features load, memory.','performance','active',3),
  (s29,p_id,'TS-029','Security','Unauth blocked, non-admin denied, no secrets exposed.','security','active',3),
  (s30,p_id,'TS-030','Accessibility','Keyboard nav, contrast, form labels.','accessibility','active',3),
  (s31,p_id,'TS-031','Responsive Layout','Tablet 768px, mobile 375px, marketing pages.','ui','active',3),
  (s32,p_id,'TS-032','Mission Control Layout','Pattern A compliance, fixed headers, no overflow.','ui','active',3),
  (s33,p_id,'TS-033','Scroll Container Validation','Single scroll per page, split panels, modal scroll.','ui','active',3),
  (s34,p_id,'TS-034','Error Handling','API error states, empty states, form validation.','engineering','active',3);

INSERT INTO ecc_test_cases
  (suite_id,plan_id,case_number,title,description,steps,expected_result,status,test_type,severity)
VALUES
-- Authentication (s01)
(s01,p_id,'TP001-TC-001','Admin login with valid credentials',
 'Verify admin can sign in with email and password.',
 '1. Navigate to /login. 2. Enter valid admin email and password. 3. Click Sign In.',
 'Admin is authenticated and redirected to the admin dashboard.','pending','manual','critical'),
(s01,p_id,'TP001-TC-002','Admin OTP verification flow',
 'Verify OTP screen is presented and validated on admin login.',
 '1. Complete password login. 2. Wait for OTP screen. 3. Enter valid OTP code. 4. Confirm access.',
 'Admin gains full access after OTP verification.','pending','manual','critical'),
(s01,p_id,'TP001-TC-003','Session persistence across page reload',
 'Verify authenticated session is retained after browser reload.',
 '1. Log in as admin. 2. Reload the browser tab.',
 'Admin remains authenticated — no re-login prompt.','pending','manual','high'),
-- Mission Control (s02)
(s02,p_id,'TP001-TC-004','Mission Control dashboard loads without error',
 'Verify Mission Control loads all sections with live data and no error states.',
 '1. Navigate to ECC > Mission Control. 2. Wait for all sections to load. 3. Verify no error banners.',
 'All sections display with data. No loading spinners remain. No error states visible.','pending','manual','critical'),
(s02,p_id,'TP001-TC-005','Engineering Health widget displays correctly',
 'Verify the Engineering Guardian health widget shows latest review data.',
 '1. Open Mission Control. 2. Scroll to Engineering Health section. 3. Check score and breakdown.',
 'Health score, breakdown bars, open issues, and approval status display correctly.','pending','manual','high'),
(s02,p_id,'TP001-TC-006','Mission Control navigation links function',
 'Verify all navigation links in Mission Control widgets redirect correctly.',
 '1. Click each View / ArrowRight navigation link in Mission Control widgets.',
 'Every link navigates to the correct ECC section without error.','pending','manual','medium'),
-- CEO Dashboard (s03)
(s03,p_id,'TP001-TC-007','CEO Dashboard loads without error',
 'Verify CEO Dashboard is accessible and renders all metric cards.',
 '1. Navigate to the main Dashboard page. 2. Wait for metrics to load.',
 'Dashboard loads with all metric cards visible and populated.','pending','manual','medium'),
(s03,p_id,'TP001-TC-008','CEO Dashboard key metrics match ECC data',
 'Verify metrics shown on CEO Dashboard match live database state.',
 '1. Note feature count on Dashboard. 2. Compare against Features page count.',
 'Dashboard metrics are consistent with ECC source tables within acceptable variance.','pending','manual','medium'),
(s03,p_id,'TP001-TC-009','No duplicate data sources on CEO Dashboard',
 'Verify CEO Dashboard reads from canonical sources only.',
 '1. Review all data widgets on CEO Dashboard. 2. Identify their data sources.',
 'All widgets source data from canonical ECC tables — no duplicated or conflicting reads.','pending','manual','low'),
-- AI Technical Director (s04)
(s04,p_id,'TP001-TC-010','AI Technical Director responds to engineering queries',
 'Verify AI TD returns a relevant response to an engineering question.',
 '1. Open Mission Control > AI Advisor tab. 2. Submit a platform engineering question.',
 'AI TD returns a coherent, relevant response within 30 seconds.','pending','manual','high'),
(s04,p_id,'TP001-TC-011','AI TD references correct platform context',
 'Verify AI TD response mentions actual platform features and release state.',
 '1. Ask AI TD about the current release status.',
 'Response references the correct active release candidate and engineering state.','pending','manual','high'),
(s04,p_id,'TP001-TC-012','AI TD usage is logged in ai_usage_log',
 'Verify all AI TD calls create ai_usage_log records.',
 '1. Make an AI TD query. 2. Navigate to AI Platform > Usage. 3. Check log.',
 'New ai_usage_log entry appears with feature = command-centre-ai and correct tokens.','pending','manual','medium'),
-- Engineering Guardian (s05)
(s05,p_id,'TP001-TC-013','Engineering Guardian review submits and completes',
 'Verify a new review can be submitted and the AI analysis completes without error.',
 '1. Open Engineering Guardian. 2. Click New Review. 3. Fill title, change type, summary. 4. Click Run.',
 'Review is created, AI runs, result is stored. No "Failed to fetch" error.','pending','manual','critical'),
(s05,p_id,'TP001-TC-014','Guardian review detail panel shows all three tabs',
 'Verify review detail shows Overview, Report, and Evidence tabs with complete data.',
 '1. Click an existing review. 2. Switch between Overview, Report, and Evidence tabs.',
 'All three tabs load. Report tab shows full 18-section markdown. Evidence tab shows findings.','pending','manual','high'),
(s05,p_id,'TP001-TC-015','Guardian PO approval workflow updates status',
 'Verify Product Owner can approve or reject a guardian review.',
 '1. Open a pending review. 2. Click Approve or Reject. 3. Confirm action.',
 'approval_status updates. Status badge in review list reflects the change.','pending','manual','high'),
-- Engineering Documentation (s06)
(s06,p_id,'TP001-TC-016','Documentation section loads all document types',
 'Verify Engineering Documentation section renders ADRs, guides, and standards.',
 '1. Navigate to ECC > Documentation. 2. Browse each document type.',
 'All document types render. No empty sections where data is expected.','pending','manual','high'),
(s06,p_id,'TP001-TC-017','New documentation entry can be created and saved',
 'Verify a new document can be added to the Documentation Engine.',
 '1. Click New Document or equivalent. 2. Fill in details. 3. Save.',
 'New document appears in the document list with correct title and type.','pending','manual','medium'),
(s06,p_id,'TP001-TC-018','Documentation can be linked to releases and features',
 'Verify documentation supports release and feature linkage.',
 '1. Open a document. 2. Add a release link. 3. Add a feature link. 4. Save.',
 'Links are persisted and navigable from the document detail.','pending','manual','medium'),
-- Engineering Change Log (s07)
(s07,p_id,'TP001-TC-019','Change Log displays all historical entries',
 'Verify Change Log shows historical migration records CL-0001 through current.',
 '1. Navigate to ECC > Change Log. 2. Scroll through entries. 3. Verify historical records visible.',
 'Historical entries display. Sequence IDs are present. No missing gaps in the log.','pending','manual','high'),
(s07,p_id,'TP001-TC-020','New change log entry can be created',
 'Verify a new change log entry can be submitted via New Entry.',
 '1. Click New Entry. 2. Fill in change title, category, description. 3. Save.',
 'New entry is created with sequential CL number and appears at top of the list.','pending','manual','high'),
(s07,p_id,'TP001-TC-021','Change Log search and category filter function',
 'Verify search and category filter narrow results correctly.',
 '1. Enter a search term. 2. Apply category filter. 3. Clear all filters.',
 'Results update accurately with search. Filter narrows correctly. Clear restores all entries.','pending','manual','medium'),
-- Product Audit (s08)
(s08,p_id,'TP001-TC-022','Product Audit feature health metrics display',
 'Verify Feature Health page renders all metrics and feature health data.',
 '1. Navigate to ECC > Feature Health. 2. Review metrics dashboard. 3. Check feature list.',
 'Feature health metrics, lifecycle stages, and category breakdown display correctly.','pending','manual','high'),
(s08,p_id,'TP001-TC-023','Product Audit Engineering Guardian summary bar shows',
 'Verify Guardian summary bar appears after a review is completed.',
 '1. Ensure at least one guardian review exists. 2. Navigate to Feature Health.',
 'Guardian summary bar shows health score, approval status, and View link.','pending','manual','medium'),
(s08,p_id,'TP001-TC-024','Product Audit TP-001 widget shows after execution',
 'Verify TP-001 widget appears in Feature Health after a completed execution.',
 '1. Complete a TP-001 execution. 2. Navigate to Feature Health.',
 'TP-001 bar shows pass rate, release recommendation, and link to TP-001 page.','pending','manual','medium'),
-- Engineering Programme (s09)
(s09,p_id,'TP001-TC-025','Dev Programme phases display with correct status',
 'Verify Engineering Programme shows all phases with status and progress.',
 '1. Navigate to ECC > Dev Programme. 2. Review all phases.',
 'All phases visible with correct status, phase numbers, and linked release candidates.','pending','manual','high'),
(s09,p_id,'TP001-TC-026','Phase RC linkage is correct and navigable',
 'Verify Dev Programme phases link to the correct release candidates.',
 '1. Open a phase. 2. Check the linked RC. 3. Navigate to the release.',
 'RC link is correct. Navigation to Release Centre opens the correct RC.','pending','manual','medium'),
(s09,p_id,'TP001-TC-027','EOS engineering stages track phase progression',
 'Verify Engineering Excellence Stages reflect current phase completion.',
 '1. Open a phase. 2. Review EOS stages. 3. Check stage completion status.',
 'EOS stages reflect current phase progress accurately — no stale or incorrect statuses.','pending','manual','medium'),
-- Goals & Epics (s10)
(s10,p_id,'TP001-TC-028','Goals & Epics loads goal hierarchy',
 'Verify Goals & Epics page loads the goal/epic/story hierarchy.',
 '1. Navigate to ECC > Goals & Epics. 2. Review the goal hierarchy.',
 'Goals, linked epics, and child items display in correct hierarchy.','pending','manual','medium'),
(s10,p_id,'TP001-TC-029','New goal can be created',
 'Verify a new goal can be saved through the creation form.',
 '1. Click New Goal. 2. Fill in title and description. 3. Save.',
 'New goal appears in the goals list with correct status.','pending','manual','medium'),
(s10,p_id,'TP001-TC-030','Epics display correctly under parent goals',
 'Verify epics are correctly parented under their goals.',
 '1. Expand a goal. 2. Review linked epics.',
 'Epics display under the correct parent goal. Links are navigable.','pending','manual','low'),
-- Roadmap (s11)
(s11,p_id,'TP001-TC-031','Roadmap displays all active items with themes',
 'Verify Roadmap page shows all items with correct theme and status.',
 '1. Navigate to ECC > Roadmap. 2. Review all roadmap items.',
 'All active roadmap items visible with themes, status, and priority.','pending','manual','medium'),
(s11,p_id,'TP001-TC-032','Roadmap filtering by theme and status works',
 'Verify filter controls narrow roadmap items correctly.',
 '1. Apply theme filter. 2. Apply status filter. 3. Clear all.',
 'Items filter correctly. Clear all restores full list.','pending','manual','medium'),
(s11,p_id,'TP001-TC-033','Roadmap items link to releases correctly',
 'Verify roadmap item release linkage is correct.',
 '1. Open a roadmap item. 2. Check linked release. 3. Navigate to release.',
 'Release link points to correct RC. Navigation opens the correct release.','pending','manual','low'),
-- Ideas & Backlog (s12)
(s12,p_id,'TP001-TC-034','Ideas & Backlog loads and filters correctly',
 'Verify backlog page shows items with working status and priority filters.',
 '1. Navigate to ECC > Ideas & Backlog. 2. Apply status and priority filters.',
 'Items display. Filters narrow results accurately.','pending','manual','medium'),
(s12,p_id,'TP001-TC-035','New backlog item can be created',
 'Verify a new backlog item can be submitted.',
 '1. Click New Item. 2. Fill in title and priority. 3. Save.',
 'New item appears in the backlog list with the correct priority badge.','pending','manual','medium'),
(s12,p_id,'TP001-TC-036','Backlog search returns relevant results',
 'Verify backlog search narrows results to matching titles.',
 '1. Enter a search term. 2. Review results. 3. Clear search.',
 'Search returns matching items only. Clear restores full list.','pending','manual','low'),
-- Features (s13)
(s13,p_id,'TP001-TC-037','Features page loads full feature registry',
 'Verify Features page shows all 80+ features with lifecycle stages.',
 '1. Navigate to ECC > Features. 2. Review feature list grouped by category.',
 'All feature categories render with correct lifecycle stage indicators.','pending','manual','high'),
(s13,p_id,'TP001-TC-038','Feature detail panel shows all data tabs',
 'Verify feature detail panel renders Overview, Testing, Versions, and Relationships tabs.',
 '1. Click a feature. 2. Review each detail tab.',
 'All tabs load with relevant data. No empty-tab errors.','pending','manual','medium'),
(s13,p_id,'TP001-TC-039','Feature lifecycle stage can be updated',
 'Verify feature lifecycle stage can be changed and persisted.',
 '1. Open a feature. 2. Change lifecycle stage. 3. Save.',
 'Lifecycle stage updates and the change is reflected in the features list.','pending','manual','medium'),
-- Releases (s14)
(s14,p_id,'TP001-TC-040','Release Centre shows active release candidate',
 'Verify Release Centre highlights the current active RC correctly.',
 '1. Navigate to ECC > Releases. 2. Identify the active RC.',
 'Current RC is highlighted with is_active = true badge. Correct phase name shown.','pending','manual','critical'),
(s14,p_id,'TP001-TC-041','Release Gate shows accurate pass/fail for all gates',
 'Verify Release Gate tab evaluates all configured gates with live data.',
 '1. Navigate to Releases > Engineering Gate tab. 2. Review each gate result.',
 'Each gate shows correct pass/fail/warn based on current platform state.','pending','manual','critical'),
(s14,p_id,'TP001-TC-042','Release checklist mandatory items are addressed',
 'Verify all mandatory checklist items are marked pass or NA before release.',
 '1. Open Releases > Checklist tab. 2. Review mandatory items.',
 'No mandatory items remain in pending or fail state.','pending','manual','high'),
-- Testing Framework (s15)
(s15,p_id,'TP001-TC-043','Testing Framework dashboard loads with metrics',
 'Verify Testing Framework hub loads metrics, coverage, and RC readiness.',
 '1. Navigate to ECC > Testing Framework. 2. Review the Dashboard tab.',
 'Testing metrics, defect summary, coverage chart, and RC readiness display.','pending','manual','high'),
(s15,p_id,'TP001-TC-044','TP-001 Release Validation is accessible from Testing Framework',
 'Verify TP-001 page is navigable from the Testing Framework context.',
 '1. Navigate to Testing Framework. 2. Confirm TP-001 nav item exists and navigates correctly.',
 'TP-001 section is accessible and loads the Release Validation Suite page.','pending','manual','high'),
(s15,p_id,'TP001-TC-045','Test plans and cases reflect current platform scope',
 'Verify TP-001 test cases are current and no deprecated items remain.',
 '1. Open Testing Framework > Plans > TP-001. 2. Review all 102 cases.',
 'All 102 cases are present. No obsolete cases reference removed features.','pending','manual','medium'),
-- Engineering Audits (s16)
(s16,p_id,'TP001-TC-046','Engineering Audits page loads audit records',
 'Verify Engineering Audits shows AUD-001, AUD-002, and any subsequent audits.',
 '1. Navigate to ECC > Engineering Audits. 2. Review audit list.',
 'AUD-001 and AUD-002 visible with correct status. Filters function.','pending','manual','high'),
(s16,p_id,'TP001-TC-047','Audit detail shows findings and recommendations',
 'Verify audit detail page renders findings, risks, and recommendations.',
 '1. Open an audit. 2. Review findings. 3. Check recommendations tab.',
 'Findings are categorised. Recommendations are visible and actionable.','pending','manual','medium'),
(s16,p_id,'TP001-TC-048','Audit approval workflow updates status',
 'Verify audits can be approved through the PO review workflow.',
 '1. Open an audit pending approval. 2. Click Approve. 3. Confirm.',
 'Audit status updates to approved with reviewer name and timestamp.','pending','manual','medium'),
-- Documentation (s17)
(s17,p_id,'TP001-TC-049','Documentation section loads all document types',
 'Verify all documentation types render and are browsable.',
 '1. Navigate to ECC > Documentation. 2. Browse ADRs, guides, references, standards.',
 'All document types render with correct content. No 404 or empty sections.','pending','manual','medium'),
(s17,p_id,'TP001-TC-050','ADR-001 Core Architecture is accessible and current',
 'Verify ADR-001 is present and documents current architectural decisions.',
 '1. Open Documentation > Architecture. 2. Find and open ADR-001.',
 'ADR-001 is present with complete decision rationale and status.','pending','manual','medium'),
(s17,p_id,'TP001-TC-051','Release notes documentation exists for current release',
 'Verify release notes exist for the current RC version.',
 '1. Search documentation for the current release version. 2. Review release notes content.',
 'Release notes document exists and covers major changes in the current release.','pending','manual','high'),
-- Knowledge Centre (s18)
(s18,p_id,'TP001-TC-052','Engineering standards are documented and accessible',
 'Verify engineering standards are visible and complete.',
 '1. Navigate to ECC > Documentation or Standards. 2. Review the standards list.',
 'Engineering standards display with categories, versions, and descriptions.','pending','manual','medium'),
(s18,p_id,'TP001-TC-053','Decision log is current and categorised',
 'Verify Decision Log shows recent decisions with correct categories.',
 '1. Open Decision Log. 2. Review entries. 3. Check categories and status.',
 'Decision log shows recent decisions. Categories are consistent. Status is up to date.','pending','manual','medium'),
(s18,p_id,'TP001-TC-054','Architecture journal entries are present',
 'Verify architecture journal captures recent engineering decisions.',
 '1. Navigate to relevant journal section. 2. Review recent entries.',
 'Recent architecture decisions are journalled with timestamps and context.','pending','manual','low'),
-- Settings (s19)
(s19,p_id,'TP001-TC-055','Settings page loads all configuration sections',
 'Verify Settings page renders all tabs without error.',
 '1. Navigate to Settings. 2. Open each settings tab.',
 'All settings sections load. No missing or erroring sections.','pending','manual','medium'),
(s19,p_id,'TP001-TC-056','Environment setting matches deployment environment',
 'Verify the platform environment setting is correct for this release.',
 '1. Check environment setting in Platform Operations. 2. Compare to deployment.',
 'Environment setting matches intended deployment (production/staging/development).','pending','manual','high'),
(s19,p_id,'TP001-TC-057','OTP authentication setting is correctly configured',
 'Verify OTP enable/disable reflects the intended admin auth security policy.',
 '1. Check OTP enabled/disabled setting. 2. Confirm against security policy.',
 'OTP setting reflects the documented admin authentication security requirement.','pending','manual','high'),
-- AI Providers (s20)
(s20,p_id,'TP001-TC-058','Default AI provider is configured and active',
 'Verify a default AI provider has is_enabled = true and has_api_key = true.',
 '1. Navigate to AI Platform > Providers. 2. Check default provider status.',
 'Default provider shows is_enabled and has_api_key both true.','pending','manual','critical'),
(s20,p_id,'TP001-TC-059','AI provider health check passes',
 'Verify the active AI provider returns a passing health check.',
 '1. Navigate to AI Providers. 2. Run health check on the default provider.',
 'Health check returns success with correct model name and response time.','pending','manual','critical'),
(s20,p_id,'TP001-TC-060','AI usage is tracked and visible in AI Platform',
 'Verify AI usage log records are visible with cost and token data.',
 '1. Navigate to AI Platform > Usage. 2. Review usage log entries.',
 'Recent AI calls appear with provider, model, token count, and estimated cost.','pending','manual','high'),
-- Navigation (s21)
(s21,p_id,'TP001-TC-061','All ECC navigation items resolve correctly',
 'Verify every sidebar navigation item loads the correct page.',
 '1. Click every navigation item in the ECC sidebar in sequence.',
 'Every item loads the correct page. No 404 or default fallback shown.','pending','manual','critical'),
(s21,p_id,'TP001-TC-062','Mobile navigation opens and closes correctly',
 'Verify mobile sidebar opens, shows items, and closes on small viewport.',
 '1. Resize browser to 375px width. 2. Click hamburger. 3. Verify items. 4. Close.',
 'Sidebar opens with all nav items. Overlay closes sidebar when tapped outside.','pending','manual','high'),
(s21,p_id,'TP001-TC-063','Active navigation item is consistently highlighted',
 'Verify the active section is visually highlighted in the sidebar.',
 '1. Navigate to multiple ECC sections in sequence.',
 'Active section is highlighted in the sidebar for every section visited.','pending','manual','medium'),
-- Search (s22)
(s22,p_id,'TP001-TC-064','Search returns relevant results for known terms',
 'Verify search returns results that match the query term.',
 '1. Open search. 2. Enter a known feature or section name.',
 'Relevant results are returned. Results match the search term.','pending','manual','medium'),
(s22,p_id,'TP001-TC-065','Search result navigation goes to the correct item',
 'Verify clicking a search result navigates to the correct record.',
 '1. Search for an item. 2. Click on a result.',
 'Navigation goes to the correct record or section in the ECC.','pending','manual','medium'),
(s22,p_id,'TP001-TC-066','Empty search shows helpful empty state',
 'Verify a no-results search shows an empty state message.',
 '1. Enter a clearly non-existent search term.',
 'Empty state message is shown. No error thrown. No blank screen.','pending','manual','low'),
-- Reporting (s23)
(s23,p_id,'TP001-TC-067','Engineering Guardian report is copyable',
 'Verify the Guardian review markdown report can be copied to clipboard.',
 '1. Open a Guardian review. 2. Navigate to Report tab. 3. Click Copy.',
 'Full 18-section markdown report is copied to clipboard without error.','pending','manual','high'),
(s23,p_id,'TP001-TC-068','TP-001 execution report is generated and copyable',
 'Verify completing a TP-001 execution generates a copyable markdown report.',
 '1. Complete a TP-001 execution. 2. Open report. 3. Click Copy Report.',
 'Full TP-001 report is generated with all required sections and copies correctly.','pending','manual','high'),
(s23,p_id,'TP001-TC-069','Engineering Audit report contains all required sections',
 'Verify platform audit reports include all mandatory sections.',
 '1. Open an Engineering Audit. 2. Review the report structure.',
 'Audit report has Executive Summary, Findings, Timeline, Risks, and Recommendations.','pending','manual','medium'),
-- Shared Data Layer (s24)
(s24,p_id,'TP001-TC-070','Active RC context is consistent across all ECC pages',
 'Verify useActiveRC hook returns the same RC on all pages that display it.',
 '1. Check the active RC indicator on Mission Control, Releases, and Testing Framework.',
 'Active RC is consistently shown on all pages — same number and phase name.','pending','manual','high'),
(s24,p_id,'TP001-TC-071','Single shared Supabase client is used across the app',
 'Verify all pages use lib/supabase.ts — no duplicate client instantiation.',
 '1. Review browser network tab API calls. 2. Confirm single Supabase URL endpoint.',
 'All API calls go to a single Supabase project URL. No duplicate client endpoints.','pending','manual','medium'),
(s24,p_id,'TP001-TC-072','All AI calls are captured in ai_usage_log',
 'Verify Guardian, AI TD, and Playground calls all log to ai_usage_log.',
 '1. Make calls to Guardian, AI TD, and AI Playground. 2. Check AI Platform > Usage.',
 'All three feature names appear in ai_usage_log with correct provider and token data.','pending','manual','medium'),
-- Database (s25)
(s25,p_id,'TP001-TC-073','All required ECC tables exist and load without error',
 'Verify all ECC sections load data without missing table errors.',
 '1. Navigate to every ECC section. 2. Confirm data loads without DB errors.',
 'No table-missing or column-missing errors in any ECC section.','pending','manual','critical'),
(s25,p_id,'TP001-TC-074','RLS policies allow authenticated admin access to all tables',
 'Verify authenticated admin can read all ECC tables without RLS rejection.',
 '1. Log in as admin. 2. Open all ECC sections. 3. Check browser console for auth errors.',
 'All sections load data. No RLS rejection errors in browser console.','pending','manual','critical'),
(s25,p_id,'TP001-TC-075','No orphaned records in key relational tables',
 'Verify referential integrity in key ECC table relationships.',
 '1. Check releases for orphaned phase links. 2. Check features for orphaned RC links.',
 'No broken foreign key references cause data rendering failures.','pending','manual','high'),
-- Supabase Edge Functions (s26)
(s26,p_id,'TP001-TC-076','Architecture Guardian edge function completes successfully',
 'Verify architecture-guardian function accepts requests and returns a review.',
 '1. Submit a new Guardian review with valid inputs.',
 'Review completes within 60 seconds. No fetch, CORS, or auth error.','pending','manual','critical'),
(s26,p_id,'TP001-TC-077','AI provider test function returns correct health status',
 'Verify the test-ai-provider-connection function returns a health result.',
 '1. Run AI provider health check. 2. Observe response.',
 'Function returns 200 with a status field and latency measurement.','pending','manual','high'),
(s26,p_id,'TP001-TC-078','All edge function responses include CORS headers',
 'Verify edge functions return Access-Control-Allow-Origin on all responses.',
 '1. Open DevTools Network tab. 2. Inspect responses from edge function calls.',
 'Every edge function response includes Access-Control-Allow-Origin: *.','pending','manual','high'),
-- Integrations (s27)
(s27,p_id,'TP001-TC-079','aXcelerate integration status is documented',
 'Verify aXcelerate integration configuration and status is visible.',
 '1. Navigate to Platform Operations > Integrations. 2. Check aXcelerate section.',
 'aXcelerate integration status visible — connected or clearly not configured.','pending','manual','medium'),
(s27,p_id,'TP001-TC-080','Email integration is configured and logs recent activity',
 'Verify email queue settings are configured and activity is logged.',
 '1. Check email settings in Platform Operations. 2. Review Email Activity log.',
 'Email integration status is visible. Recent sends show in activity log.','pending','manual','medium'),
(s27,p_id,'TP001-TC-081','Stripe billing page loads without integration errors',
 'Verify Stripe billing integration is operational for the admin view.',
 '1. Navigate to Billing page. 2. Review subscription and plan display.',
 'Billing page loads without Stripe API error. Plan information is visible.','pending','manual','medium'),
-- Performance (s28)
(s28,p_id,'TP001-TC-082','Mission Control loads within 5 seconds',
 'Verify Mission Control reaches interactive state within 5 seconds on reload.',
 '1. Hard-reload Mission Control (Ctrl+Shift+R). 2. Measure time to interactive.',
 'Mission Control is fully interactive within 5 seconds on a standard connection.','pending','manual','high'),
(s28,p_id,'TP001-TC-083','Features page loads full registry within 3 seconds',
 'Verify Features page renders all features without excessive delay.',
 '1. Hard-reload Features page. 2. Measure time for all features to render.',
 'All features are visible within 3 seconds on a standard connection.','pending','manual','high'),
(s28,p_id,'TP001-TC-084','ECC memory remains stable over extended use',
 'Verify no progressive memory growth during a 10-minute ECC session.',
 '1. Open DevTools Performance/Memory. 2. Navigate through all ECC sections. 3. Observe memory.',
 'Browser memory remains stable — no progressive growth pattern observed.','pending','manual','medium'),
-- Security (s29)
(s29,p_id,'TP001-TC-085','Unauthenticated access to ECC is blocked',
 'Verify ECC sections are inaccessible without authentication.',
 '1. Sign out. 2. Attempt to navigate directly to an ECC URL.',
 'Redirected to login. No ECC content accessible without authentication.','pending','manual','critical'),
(s29,p_id,'TP001-TC-086','Non-admin accounts cannot access ECC',
 'Verify standard user accounts are denied access to the Engineering Control Centre.',
 '1. Log in with a non-admin account. 2. Attempt to access ECC.',
 'Non-admin user is denied access or shown an appropriate restriction message.','pending','manual','critical'),
(s29,p_id,'TP001-TC-087','No secrets or API keys exposed in client-side code',
 'Verify no service-role keys or API secrets are visible in browser DevTools.',
 '1. Open DevTools. 2. Review Network requests, Local Storage, and Application tab.',
 'No service role keys, API keys, or secrets visible in browser-accessible storage.','pending','manual','critical'),
-- Accessibility (s30)
(s30,p_id,'TP001-TC-088','Core ECC actions are keyboard-navigable',
 'Verify primary ECC actions can be reached and triggered with keyboard only.',
 '1. Tab through Mission Control and Features pages using keyboard only.',
 'Primary interactive elements (buttons, links, inputs) are keyboard-accessible.','pending','manual','medium'),
(s30,p_id,'TP001-TC-089','Text contrast meets minimum requirements on key pages',
 'Verify sufficient contrast ratio on primary content in ECC.',
 '1. Review ECC pages using DevTools accessibility checker.',
 'No critical contrast violations on primary content, headings, or navigation.','pending','manual','medium'),
(s30,p_id,'TP001-TC-090','Form inputs have accessible labels or aria-labels',
 'Verify inputs have associated labels on key ECC forms.',
 '1. Inspect form inputs on Features, Guardian New Review, and Change Log forms.',
 'All inputs have a label element or aria-label attribute.','pending','manual','medium'),
-- Responsive Layout (s31)
(s31,p_id,'TP001-TC-091','ECC is functional on tablet viewport (768px)',
 'Verify ECC layout is usable on tablet-width viewport.',
 '1. Resize browser to 768px. 2. Navigate through ECC sections.',
 'ECC is usable. No broken layouts or unintended horizontal overflow.','pending','manual','high'),
(s31,p_id,'TP001-TC-092','ECC is functional on mobile viewport (375px)',
 'Verify ECC layout is functional on mobile-width viewport.',
 '1. Resize to 375px. 2. Open sidebar. 3. Navigate to multiple sections.',
 'Sidebar, content, and primary actions are accessible on mobile.','pending','manual','high'),
(s31,p_id,'TP001-TC-093','Marketing pages are responsive on mobile',
 'Verify public-facing pages reflow correctly on mobile.',
 '1. Resize to 375px. 2. Review Home, Pricing, and Features marketing pages.',
 'Marketing pages reflow correctly. No horizontal scrollbar. All content accessible.','pending','manual','medium'),
-- Mission Control Layout (s32)
(s32,p_id,'TP001-TC-094','Full-height ECC pages use Pattern A layout',
 'Verify full-height pages implement flex flex-col h-full with correct sub-patterns.',
 '1. Navigate to Mission Control, Features, Audits, and Guardian pages.',
 'All full-height pages use shrink-0 header + flex-1 overflow-y-auto body. No layout breaks.','pending','manual','high'),
(s32,p_id,'TP001-TC-095','Page headers remain fixed during content scroll',
 'Verify headers stay visible as content body scrolls.',
 '1. Open a full-height page with long content. 2. Scroll body content.',
 'Page header remains visible and fixed. Does not scroll out of view.','pending','manual','high'),
(s32,p_id,'TP001-TC-096','No unintended horizontal overflow on any ECC page',
 'Verify no ECC page produces an unwanted horizontal scrollbar.',
 '1. Navigate all ECC sections. 2. Check for horizontal scrollbars.',
 'No horizontal scrollbar appears on any ECC section at desktop viewport.','pending','manual','high'),
-- Scroll Container Validation (s33)
(s33,p_id,'TP001-TC-097','Each full-height page has exactly one scroll region',
 'Verify no nested or duplicate scroll containers exist on full-height pages.',
 '1. Open each full-height ECC page. 2. Check for multiple scrollable regions.',
 'Each page has a single scroll region — no nested overflow-y-auto/scroll containers.','pending','manual','high'),
(s33,p_id,'TP001-TC-098','Split-pane pages scroll list and detail independently',
 'Verify left list and right detail panels scroll independently.',
 '1. Open a split-pane page (Features, Guardian, Change Log). 2. Scroll each panel.',
 'List and detail panels scroll independently without causing the other to scroll.','pending','manual','high'),
(s33,p_id,'TP001-TC-099','Form modals with long content are internally scrollable',
 'Verify modals with overflow content scroll within the modal.',
 '1. Open a long form modal (New Guardian Review, New Change Log Entry). 2. Scroll.',
 'Modal content scrolls within the modal frame — does not overflow the viewport.','pending','manual','medium'),
-- Error Handling (s34)
(s34,p_id,'TP001-TC-100','API errors display user-friendly error states',
 'Verify DB or network failures show readable messages, not blank screens.',
 '1. Check error state rendering — simulate by revoking API key or viewing offline mode.',
 'Error states show a clear message with guidance. No silent failures or white screens.','pending','manual','high'),
(s34,p_id,'TP001-TC-101','Empty states display correctly on all ECC pages',
 'Verify all pages show helpful empty state UI when no data is present.',
 '1. Open pages with no data (fresh state). 2. Verify empty state message and actions.',
 'All pages show correct empty state with actionable guidance — no broken layouts.','pending','manual','medium'),
(s34,p_id,'TP001-TC-102','Form validation prevents invalid submissions',
 'Verify required fields are validated and invalid forms cannot be submitted.',
 '1. Attempt to submit key forms without filling required fields.',
 'Forms show validation errors. Submit is blocked until required fields are filled.','pending','manual','high');

END $$;
