
-- Seed 52 new UoCs across TLI, BSB (additional), CHC (additional), CPC (additional), SIT (additional), ICT (additional)
-- Using ON CONFLICT (uoc_code) DO UPDATE for idempotency

INSERT INTO uoc_acsf_library (
  uoc_code, uoc_title, training_package,
  learning_level, reading_level, writing_level, oral_comm_level, numeracy_level, digital_level,
  source_type, industry_tag, task_tags, complexity_indicators, evidence_basis, confidence, last_updated
) VALUES

-- ─── TLI: Transport & Logistics (12 units) ────────────────────────────────────
('TLIF1001', 'Follow work health and safety procedures', 'TLI',
  2, 2, 2, 2, 2, 1,
  'validated', 'Transport & Logistics',
  ARRAY['WHS procedures','hazard reporting','PPE compliance'],
  ARRAY['safety documentation','incident forms','workplace signage'],
  'TLI Training Package safety unit — Cert II entry-level WHS. Reading and writing demands are basic procedural.', 'high', now()),

('TLIA0004', 'Sort and process mail', 'TLI',
  2, 2, 2, 1, 2, 2,
  'validated', 'Transport & Logistics',
  ARRAY['mail sorting','address reading','postal systems'],
  ARRAY['address identification','sorting codes','basic numerical sorting'],
  'TLI postal/logistics unit requiring address reading and basic sorting accuracy.', 'high', now()),

('TLIA0007', 'Receive and store stock', 'TLI',
  2, 2, 2, 2, 2, 2,
  'validated', 'Transport & Logistics',
  ARRAY['stock receiving','inventory','storage procedures'],
  ARRAY['delivery documentation','quantity checking','stock records'],
  'TLI warehousing unit — Cert II. Involves checking delivery dockets, counting, recording discrepancies.', 'high', now()),

('TLIA3025', 'Conduct stocktaking procedures', 'TLI',
  3, 3, 3, 2, 3, 2,
  'validated', 'Transport & Logistics',
  ARRAY['stocktaking','inventory reconciliation','discrepancy reporting'],
  ARRAY['numerical counting','inventory systems','discrepancy documentation'],
  'TLI Cert III stocktaking requiring numerical accuracy, inventory system use, and reconciliation reporting.', 'high', now()),

('TLILIC0001', 'Licence to operate a forklift truck', 'TLI',
  2, 2, 2, 2, 2, 1,
  'validated', 'Transport & Logistics',
  ARRAY['forklift operation','load handling','pre-operational checks'],
  ARRAY['safety checklists','load calculations','operational documentation'],
  'TLI high-risk work licence unit. Reading safety procedures, completing checklists, basic load weight calculations.', 'high', now()),

('TLIF0015', 'Implement and monitor environmentally sustainable work practices', 'TLI',
  3, 3, 3, 2, 2, 2,
  'validated', 'Transport & Logistics',
  ARRAY['sustainability','waste management','environmental compliance'],
  ARRAY['environmental reporting','waste logs','regulatory documentation'],
  'TLI sustainability unit — Cert III. Requires reading environmental legislation summaries and writing reports.', 'high', now()),

('TLIHAZTDG200', 'Comply with regulations for the transport of dangerous goods', 'TLI',
  3, 4, 3, 2, 3, 2,
  'validated', 'Transport & Logistics',
  ARRAY['dangerous goods','ADG Code','placarding','segregation'],
  ARRAY['regulatory reading','DG documentation','emergency procedures','compliance forms'],
  'TLI dangerous goods unit requiring reading and interpreting complex ADG Code regulations and completing compliance documentation.', 'high', now()),

('TLID0012', 'Operate a vehicle to transport freight', 'TLI',
  2, 2, 2, 2, 2, 2,
  'validated', 'Transport & Logistics',
  ARRAY['vehicle operation','delivery documentation','route planning'],
  ARRAY['consignment notes','delivery dockets','GPS/navigation systems'],
  'TLI freight transport unit — Cert II. Involves reading delivery instructions, completing dockets, using digital navigation.', 'high', now()),

('TLIC0009', 'Drive light rigid vehicle', 'TLI',
  2, 2, 2, 2, 2, 2,
  'validated', 'Transport & Logistics',
  ARRAY['light rigid vehicle','traffic law','pre-trip inspection'],
  ARRAY['logbook completion','traffic regulation reading','vehicle checklists'],
  'TLI LR licence unit. Logbook keeping, reading road rules, pre-trip inspection documentation.', 'high', now()),

('TLIM0004', 'Plan and organise work', 'TLI',
  3, 3, 3, 3, 2, 2,
  'validated', 'Transport & Logistics',
  ARRAY['work planning','scheduling','task prioritisation'],
  ARRAY['work order systems','scheduling documentation','resource planning'],
  'TLI Cert III planning unit. Reading and creating work schedules, interpreting work orders, oral coordination with team.', 'high', now()),

('TLIB0001', 'Interpret and apply information from transport documents', 'TLI',
  3, 4, 3, 2, 3, 2,
  'validated', 'Transport & Logistics',
  ARRAY['transport documents','waybills','consignment notes','customs documentation'],
  ARRAY['document interpretation','data extraction','compliance checking'],
  'TLI core document literacy unit. Reading and interpreting complex freight documents including customs and dangerous goods manifests.', 'high', now()),

('TLID3001', 'Optimise load for transport', 'TLI',
  3, 3, 3, 2, 4, 2,
  'validated', 'Transport & Logistics',
  ARRAY['load optimisation','weight distribution','axle calculations','load restraint'],
  ARRAY['load calculations','weight charts','mass dimension regulations','load plans'],
  'TLI Cert III load optimisation. High numeracy demand: axle load calculations, weight distribution, compliance with mass/dimension limits.', 'high', now()),

-- ─── BSB: Additional Business Services (12 units) ─────────────────────────────
('BSBCMM311', 'Communicate with influence', 'BSB',
  3, 3, 3, 4, 2, 2,
  'validated', 'Business Services',
  ARRAY['professional communication','negotiation','stakeholder influence','persuasion'],
  ARRAY['written persuasion','oral presentations','communication strategy'],
  'BSB communication unit — Cert III/IV. High oral communication demand for presentations and negotiation.', 'high', now()),

('BSBCMM412', 'Lead difficult conversations', 'BSB',
  4, 3, 3, 4, 2, 2,
  'validated', 'Business Services',
  ARRAY['conflict resolution','difficult conversations','mediation','workplace relationships'],
  ARRAY['communication frameworks','de-escalation strategies','follow-up documentation'],
  'BSB Cert IV leadership communication. Advanced oral communication and learning about interpersonal frameworks.', 'high', now()),

('BSBDIG301', 'Create and use spreadsheets', 'BSB',
  2, 2, 3, 1, 3, 4,
  'validated', 'Business Services',
  ARRAY['spreadsheets','Excel','data entry','formulas','charts'],
  ARRAY['formula construction','data analysis','chart creation','spreadsheet documentation'],
  'BSB digital unit — Cert III. Strong numeracy and digital demands for spreadsheet formulas, data analysis, chart production.', 'high', now()),

('BSBDIG302', 'Create and use databases', 'BSB',
  3, 3, 3, 1, 3, 4,
  'validated', 'Business Services',
  ARRAY['databases','data entry','queries','reports'],
  ARRAY['database queries','report generation','data integrity','technical documentation'],
  'BSB Cert III database unit. High digital demand with moderate numeracy for data queries and structured reporting.', 'high', now()),

('BSBOPS201', 'Work effectively in business environments', 'BSB',
  2, 2, 2, 2, 1, 2,
  'validated', 'Business Services',
  ARRAY['workplace procedures','professional behaviour','time management','team communication'],
  ARRAY['workplace documentation','following instructions','professional communication'],
  'BSB foundational workplace unit — Cert II. Entry-level literacy and communication demands.', 'high', now()),

('BSBPEF501', 'Manage personal and professional development', 'BSB',
  4, 4, 4, 3, 2, 3,
  'validated', 'Business Services',
  ARRAY['professional development','CPD planning','self-assessment','career management'],
  ARRAY['reflective writing','development plans','goal setting documentation'],
  'BSB Cert IV/Diploma personal development unit. Strong literacy for reflective writing and CPD documentation.', 'high', now()),

('BSBTWK401', 'Build and maintain business relationships', 'BSB',
  3, 3, 3, 4, 2, 2,
  'validated', 'Business Services',
  ARRAY['networking','stakeholder relationships','professional communication','trust building'],
  ARRAY['relationship management frameworks','communication documentation','professional correspondence'],
  'BSB Cert IV relationships unit. High oral communication for networking and stakeholder management.', 'high', now()),

('BSBTWK502', 'Manage team effectiveness', 'BSB',
  4, 3, 4, 4, 2, 3,
  'validated', 'Business Services',
  ARRAY['team management','performance monitoring','delegation','team development'],
  ARRAY['performance reports','team plans','management communication','strategic documentation'],
  'BSB Diploma team management unit. High writing and oral demands for performance management and team strategy.', 'high', now()),

('BSBMKG433', 'Undertake marketing activities', 'BSB',
  3, 3, 3, 3, 3, 3,
  'validated', 'Business Services',
  ARRAY['marketing activities','campaign implementation','market research','social media'],
  ARRAY['marketing briefs','campaign reports','ROI analysis','digital marketing platforms'],
  'BSB Cert IV marketing unit. Balanced demands across all skills including digital for social media platforms.', 'high', now()),

('BSBTEC301', 'Design and produce business documents', 'BSB',
  3, 3, 4, 2, 2, 4,
  'validated', 'Business Services',
  ARRAY['document design','templates','word processing','desktop publishing'],
  ARRAY['document formatting','style guides','software proficiency','professional presentation'],
  'BSB Cert III document production unit. High writing and digital for advanced word processing and document design.', 'high', now()),

('BSBTEC403', 'Apply digital solutions to work processes', 'BSB',
  3, 3, 3, 2, 2, 4,
  'validated', 'Business Services',
  ARRAY['digital tools','process automation','cloud applications','digital workflows'],
  ARRAY['technology evaluation','digital solution documentation','process mapping'],
  'BSB Cert IV digital work unit. High digital for evaluating and applying technology solutions to business processes.', 'high', now()),

('BSBLEG523', 'Apply legal principles in contract law matters', 'BSB',
  4, 5, 4, 3, 2, 2,
  'validated', 'Business Services',
  ARRAY['contract law','legal documents','compliance','risk management'],
  ARRAY['legal text interpretation','contract analysis','compliance documentation','legislative reading'],
  'BSB Diploma legal unit. Very high reading for interpreting complex legal texts and contracts.', 'high', now()),

-- ─── CHC: Additional Community Services (10 units) ────────────────────────────
('CHCMHS001', 'Work with people with mental health issues', 'CHC',
  3, 3, 3, 4, 2, 2,
  'validated', 'Community Services',
  ARRAY['mental health','recovery model','psychosocial support','de-escalation'],
  ARRAY['care documentation','mental health frameworks','clinical communication'],
  'CHC mental health unit — Cert IV. High oral communication for therapeutic conversations and team communication.', 'high', now()),

('CHCMHS007', 'Work effectively in trauma informed care', 'CHC',
  4, 4, 4, 4, 2, 2,
  'validated', 'Community Services',
  ARRAY['trauma-informed care','trauma responses','safe environments','resilience'],
  ARRAY['reflective practice','clinical documentation','trauma frameworks','supervision notes'],
  'CHC Cert IV/Diploma trauma care. High literacy demands for complex documentation and evidence-based practice.', 'high', now()),

('CHCDIS012', 'Support community participation and social inclusion', 'CHC',
  3, 3, 3, 3, 2, 2,
  'validated', 'Community Services',
  ARRAY['social inclusion','community access','NDIS','participation planning'],
  ARRAY['support plans','activity documentation','goal planning','progress notes'],
  'CHC disability unit — Cert III/IV. Moderate literacy for support plans and participation documentation.', 'high', now()),

('CHCYTH011', 'Engage respectfully with young people', 'CHC',
  3, 3, 3, 4, 2, 2,
  'validated', 'Community Services',
  ARRAY['youth work','rapport building','boundary setting','strengths-based practice'],
  ARRAY['case notes','youth engagement frameworks','professional communication'],
  'CHC youth work unit — Cert IV. High oral communication for building rapport and professional boundaries with young people.', 'high', now()),

('CHCPAL001', 'Deliver care services using a palliative approach', 'CHC',
  3, 4, 3, 4, 2, 2,
  'validated', 'Community Services',
  ARRAY['palliative care','end-of-life care','family support','comfort care'],
  ARRAY['clinical care plans','end-of-life documentation','family communication','grief support'],
  'CHC palliative care unit — Cert III/IV. High reading for clinical documentation and high oral for sensitive family communication.', 'high', now()),

('CHCECE035', 'Support the holistic learning and development of children', 'CHC',
  3, 3, 3, 3, 2, 3,
  'validated', 'Community Services',
  ARRAY['holistic development','learning frameworks','developmental observation','family partnerships'],
  ARRAY['learning stories','developmental documentation','curriculum planning','observation records'],
  'CHC ECE unit — Cert III. Strong literacy for learning documentation, moderate digital for digital portfolios.', 'high', now()),

('CHCECE041', 'Maintain a safe and healthy environment for children', 'CHC',
  2, 3, 3, 2, 2, 2,
  'validated', 'Community Services',
  ARRAY['childcare safety','risk assessment','hygiene procedures','incident reporting'],
  ARRAY['safety checklists','incident documentation','regulatory compliance','risk assessments'],
  'CHC ECE safety unit — Cert III. Moderate literacy for safety documentation, reading regulations and completing incident reports.', 'high', now()),

('CHCSOH013', 'Work with people experiencing or at risk of homelessness', 'CHC',
  3, 3, 3, 4, 2, 2,
  'validated', 'Community Services',
  ARRAY['homelessness','housing access','support coordination','crisis intervention'],
  ARRAY['case management','housing referrals','support plans','service navigation'],
  'CHC social housing unit — Cert IV. High oral for crisis communication, moderate literacy for case management documentation.', 'high', now()),

('CHCAOD001', 'Work in an alcohol and other drugs context', 'CHC',
  3, 3, 3, 4, 2, 2,
  'validated', 'Community Services',
  ARRAY['AOD support','harm reduction','brief interventions','motivational interviewing'],
  ARRAY['AOD assessment tools','case notes','harm reduction frameworks','service referrals'],
  'CHC AOD unit — Cert IV. High oral communication for motivational interviewing; moderate literacy for assessment documentation.', 'high', now()),

('CHCPRT025', 'Identify and report children and young people at risk', 'CHC',
  3, 4, 4, 3, 2, 2,
  'validated', 'Community Services',
  ARRAY['child protection','mandatory reporting','risk indicators','inter-agency collaboration'],
  ARRAY['risk assessment tools','mandatory reporting procedures','legal obligations','case documentation'],
  'CHC child protection unit — Cert IV. High reading for legislative requirements, high writing for mandatory reports and case notes.', 'high', now()),

-- ─── CPC: Additional Construction (5 units) ───────────────────────────────────
('CPCCCO2013', 'Carry out concreting to simple forms', 'CPC',
  2, 2, 2, 2, 3, 1,
  'validated', 'Construction',
  ARRAY['concreting','formwork','concrete mixing','finishing'],
  ARRAY['mix calculations','measurement','technical drawings','material quantities'],
  'CPC Cert II concreting unit. Moderate numeracy for concrete mix calculations and measurements.', 'high', now()),

('CPCCPLP3012', 'Install stormwater drainage systems', 'CPC',
  3, 3, 3, 2, 3, 2,
  'validated', 'Construction',
  ARRAY['plumbing','stormwater','drainage installation','pipe fitting'],
  ARRAY['plan reading','fall calculations','compliance documentation','material specifications'],
  'CPC Cert III plumbing unit. Moderate numeracy for fall calculations; reading technical plans and specifications.', 'high', now()),

('CPCPCM2012', 'Work safely at heights', 'CPC',
  2, 2, 2, 2, 2, 1,
  'validated', 'Construction',
  ARRAY['working at heights','fall protection','harness use','rescue procedures'],
  ARRAY['safety checklists','risk assessment','procedure reading','equipment inspection forms'],
  'CPC Cert II safety unit. Basic literacy for safety procedures and equipment checklists.', 'high', now()),

('CPCCBC4053', 'Apply building codes and standards to the construction process', 'CPC',
  4, 5, 4, 3, 3, 2,
  'validated', 'Construction',
  ARRAY['NCC','building codes','compliance','standards interpretation','building regulations'],
  ARRAY['regulatory reading','compliance documentation','technical specification interpretation','building approvals'],
  'CPC Cert IV compliance unit. Very high reading for interpreting National Construction Code and building regulations.', 'high', now()),

('CPCSUS4002', 'Use building science principles to construct energy efficient buildings', 'CPC',
  4, 4, 4, 3, 4, 2,
  'validated', 'Construction',
  ARRAY['energy efficiency','NatHERS','thermal performance','sustainable construction'],
  ARRAY['energy calculations','compliance reporting','technical specifications','sustainability documentation'],
  'CPC Cert IV sustainability unit. High numeracy for energy calculations; high reading for technical standards.', 'high', now()),

-- ─── SIT: Additional Hospitality & Tourism (5 units) ─────────────────────────
('SITXHRM009', 'Lead and manage people', 'SIT',
  4, 3, 4, 4, 2, 3,
  'validated', 'Hospitality & Tourism',
  ARRAY['hospitality management','team leadership','rostering','performance feedback'],
  ARRAY['roster management','performance documentation','management communication','team reports'],
  'SIT Cert IV/Diploma leadership unit. High oral and writing for team management, roster planning, and performance documentation.', 'high', now()),

('SITXFIN009', 'Manage finances within a budget', 'SIT',
  3, 3, 4, 2, 4, 3,
  'validated', 'Hospitality & Tourism',
  ARRAY['budget management','financial reports','cost control','revenue analysis'],
  ARRAY['budget spreadsheets','variance reporting','financial analysis','P&L interpretation'],
  'SIT Cert IV financial management. High numeracy and writing for budget preparation and variance reporting.', 'high', now()),

('SITXGLC001', 'Research and comply with regulatory requirements', 'SIT',
  3, 4, 3, 2, 2, 3,
  'validated', 'Hospitality & Tourism',
  ARRAY['liquor licensing','regulatory compliance','gaming regulations','RSG'],
  ARRAY['legislation reading','compliance registers','regulatory documentation','licence conditions'],
  'SIT gaming/hospitality compliance unit. High reading for legislation; digital for compliance management systems.', 'high', now()),

('SITHCCC023', 'Use food preparation equipment', 'SIT',
  2, 2, 2, 2, 2, 1,
  'validated', 'Hospitality & Tourism',
  ARRAY['kitchen equipment','food preparation','mise en place','equipment maintenance'],
  ARRAY['recipe reading','equipment manuals','hygiene procedures','basic kitchen documentation'],
  'SIT Cert II kitchen unit. Basic literacy for recipe reading and equipment safety procedures.', 'high', now()),

('SITXINV006', 'Receive and store stock', 'SIT',
  2, 2, 2, 2, 2, 2,
  'validated', 'Hospitality & Tourism',
  ARRAY['stock control','receiving procedures','storage standards','inventory systems'],
  ARRAY['delivery dockets','stock records','temperature logs','inventory software'],
  'SIT Cert II/III stock unit. Basic literacy for delivery documentation; basic digital for inventory systems.', 'high', now()),

-- ─── ICT: Additional Information Technology (7 units) ────────────────────────
('ICTPMG505', 'Manage ICT projects', 'ICT',
  4, 4, 4, 4, 3, 4,
  'validated', 'Information Technology',
  ARRAY['IT project management','agile','PRINCE2','project documentation','stakeholder management'],
  ARRAY['project plans','risk registers','status reports','stakeholder communication','change management'],
  'ICT Diploma project management unit. High demands across all literacy skills for complex project documentation and stakeholder communication.', 'high', now()),

('ICTSAS524', 'Develop, implement and evaluate an incident response plan', 'ICT',
  4, 4, 4, 3, 2, 4,
  'validated', 'Information Technology',
  ARRAY['incident response','cybersecurity','CSIRT','forensics','breach management'],
  ARRAY['incident response plans','forensic documentation','technical reporting','regulatory notification'],
  'ICT Cert IV/Diploma security incident unit. High literacy for technical planning and reporting; high digital for security tools.', 'high', now()),

('ICTCYS606', 'Evaluate an organisation cybersecurity capability', 'ICT',
  5, 5, 5, 4, 3, 5,
  'validated', 'Information Technology',
  ARRAY['cybersecurity maturity','risk assessment','security frameworks','NIST','ISO27001'],
  ARRAY['maturity assessment reports','gap analysis','executive communication','security architecture'],
  'ICT Advanced Diploma cybersecurity evaluation. Maximum demands: complex technical writing, framework interpretation, executive reporting.', 'high', now()),

('ICTWEB431', 'Create a markup language document', 'ICT',
  3, 3, 3, 1, 2, 4,
  'validated', 'Information Technology',
  ARRAY['HTML','CSS','web development','markup','web standards'],
  ARRAY['code documentation','web standards reading','technical writing','W3C compliance'],
  'ICT Cert IV web unit. High digital for HTML/CSS; moderate literacy for technical documentation and standards interpretation.', 'high', now()),

('ICTWEB452', 'Create a website', 'ICT',
  3, 3, 4, 2, 2, 5,
  'validated', 'Information Technology',
  ARRAY['website creation','JavaScript','responsive design','CMS','UX'],
  ARRAY['technical specifications','user documentation','design documentation','testing reports'],
  'ICT Cert IV website development. Very high digital across multiple technologies; moderate writing for technical documentation.', 'high', now()),

('ICTDBS403', 'Develop and implement a database', 'ICT',
  4, 4, 4, 2, 3, 5,
  'validated', 'Information Technology',
  ARRAY['database development','SQL','normalisation','stored procedures','data security'],
  ARRAY['database design documentation','ERD diagrams','SQL scripts','technical specifications'],
  'ICT Cert IV database development. Very high digital for complex SQL and database architecture; high learning for database theory.', 'high', now()),

('ICTNWK546', 'Manage network security', 'ICT',
  4, 4, 4, 3, 3, 5,
  'validated', 'Information Technology',
  ARRAY['network security','firewall management','IDS/IPS','VPN','access control'],
  ARRAY['security policy documentation','network diagrams','audit reports','technical specifications'],
  'ICT Diploma network security. Very high digital for security tools; high literacy for security policy and audit documentation.', 'high', now())

ON CONFLICT (uoc_code) DO UPDATE SET
  uoc_title            = EXCLUDED.uoc_title,
  training_package     = EXCLUDED.training_package,
  learning_level       = EXCLUDED.learning_level,
  reading_level        = EXCLUDED.reading_level,
  writing_level        = EXCLUDED.writing_level,
  oral_comm_level      = EXCLUDED.oral_comm_level,
  numeracy_level       = EXCLUDED.numeracy_level,
  digital_level        = EXCLUDED.digital_level,
  source_type          = EXCLUDED.source_type,
  industry_tag         = EXCLUDED.industry_tag,
  task_tags            = EXCLUDED.task_tags,
  complexity_indicators = EXCLUDED.complexity_indicators,
  evidence_basis       = EXCLUDED.evidence_basis,
  confidence           = EXCLUDED.confidence,
  last_updated         = EXCLUDED.last_updated;
