
-- ─────────────────────────────────────────────────────────────────────────────
-- SEED: Assessment Engine
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO ecc_product_features (
  feature_id, name, category, sub_category, description, purpose,
  status, priority, release_version, implementation_date,
  implementation_source, source_file, developer, testing_status, production_ready,
  database_changes, api_changes, ui_changes, compliance_impact, audit_impact, security_impact,
  documentation_status, tags
) VALUES

('FEAT-010', 'Database-Driven Assessment Engine', 'Assessment Engine', 'Core',
 'Dynamic assessment engine powered by database records. Assessments and questions are stored in DB (not hardcoded), enabling version management, ACSF mapping, and independent question updates. Supports LLN and Digital assessment types.',
 'Flexible, maintainable assessment engine that can be updated without code changes.',
 'implemented', 'critical', 'v0.1', '2026-07-01 09:48:35+00',
 'Migration', 'supabase/migrations/20260701094835_seed_db_driven_assessments.sql', 'AI', 'requires_review', true,
 'assessments, assessment_questions tables (seeded with 75 LLN + 21 Digital questions)',
 NULL, 'QuizPage, LLNAssessmentPage, DigitalAssessmentPage consume DB questions',
 'ASQA: Questions are versioned and auditable', 'Question version tracked per response',
 NULL, 'partial', ARRAY['assessment', 'engine', 'database', 'lln', 'digital']),

('FEAT-011', 'LLN Assessment — 75 Question Bank', 'Assessment Engine', 'LLN',
 '75 questions across 5 ACSF domains (Reading, Numeracy, Writing, Oral Communication, Learning) at levels 1–5, with 3–4 questions per level per domain. Multiple choice and short answer formats.',
 'Provide a statistically robust question bank for Language, Literacy and Numeracy assessment.',
 'implemented', 'critical', 'v0.1', '2026-07-01 09:48:35+00',
 'Migration', 'supabase/migrations/20260701094835_seed_db_driven_assessments.sql', 'AI', 'requires_review', true,
 'assessment_questions (75 LLN rows)', NULL, 'Rendered by LLNAssessmentPage',
 'ASQA: Maps to ACSF framework', NULL, NULL,
 'partial', ARRAY['lln', 'questions', 'acsf', 'reading', 'numeracy', 'writing']),

('FEAT-012', 'Digital Capability Assessment — 21 Question Bank', 'Assessment Engine', 'Digital',
 '21 questions across 5 digital literacy domains: Basic Digital Skills, Online Communication, Information Literacy, Online Safety, Digital Problem Solving. Multiple choice format.',
 'Assess digital capability for learners entering VET qualifications requiring digital literacy.',
 'implemented', 'critical', 'v0.1', '2026-07-01 09:48:35+00',
 'Migration', 'supabase/migrations/20260701094835_seed_db_driven_assessments.sql', 'AI', 'requires_review', true,
 'assessment_questions (21 Digital rows)', NULL, 'Rendered by DigitalAssessmentPage',
 NULL, NULL, NULL,
 'partial', ARRAY['digital', 'questions', 'digital-literacy']),

('FEAT-013', 'Assessment Quiz Portal (LLN)', 'Assessment Engine', 'Student UI',
 'Token-gated student-facing portal for LLN assessment delivery. Adaptive question progression, domain-level ACSF scoring, abandonment tracking, identity verification, declaration screen.',
 'Deliver LLN assessments to candidates securely via a unique token link.',
 'implemented', 'critical', 'v0.1', '2026-06-27 00:00:00+00',
 'Component', 'src/pages/LLNAssessmentPage.tsx', 'AI', 'requires_review', true,
 'assessment_responses, assessment_invitations, student_responses, assessment_declarations',
 NULL, 'LLNAssessmentPage — full quiz UI with adaptive engine',
 'ASQA: Assessment delivery evidence', 'All responses and events logged',
 'Token-scoped RLS (x-quiz-token header)',
 'partial', ARRAY['lln', 'quiz', 'student', 'portal', 'adaptive']),

('FEAT-014', 'Assessment Quiz Portal (Digital)', 'Assessment Engine', 'Student UI',
 'Token-gated student-facing portal for Digital Capability assessment delivery. Linear question flow, domain scoring, abandonment tracking.',
 'Deliver digital literacy assessments to candidates securely via a unique token link.',
 'implemented', 'critical', 'v0.1', '2026-06-27 00:00:00+00',
 'Component', 'src/pages/DigitalAssessmentPage.tsx', 'AI', 'requires_review', true,
 'assessment_responses, assessment_invitations, student_responses',
 NULL, 'DigitalAssessmentPage — linear quiz UI',
 NULL, 'All responses and events logged',
 'Token-scoped RLS',
 'partial', ARRAY['digital', 'quiz', 'student', 'portal']),

('FEAT-015', 'Assessment Declaration Screen', 'Assessment Engine', 'Compliance',
 'Pre-assessment informed consent screen. Learner must acknowledge assessment rules and tick a checkbox before quiz begins. Declaration content and version stored in DB. Acceptance recorded with IP, user agent, timestamp.',
 'Ensure learners understand assessment conditions and provide compliant consent. ASQA requirement.',
 'implemented', 'critical', 'v0.1', '2026-07-01 02:38:25+00',
 'Migration + Component', 'src/components/AssessmentDeclarationScreen.tsx', 'AI', 'requires_review', true,
 'declaration_templates (seeded LLN v1 + Digital v1), assessment_declarations',
 NULL, 'AssessmentDeclarationScreen component shown before quiz starts',
 'ASQA: Consent and notification obligations', 'Declaration acceptance logged',
 NULL, 'partial', ARRAY['declaration', 'consent', 'compliance', 'asqa']),

('FEAT-016', 'Assessment Abandonment Tracking', 'Assessment Engine', 'Audit',
 'Detects when a student navigates away mid-quiz using visibilitychange and pagehide browser events. Logs abandonment to audit trail with timestamp and progress percentage.',
 'Maintain a complete audit record of assessment attempts including incomplete ones.',
 'implemented', 'high', 'v0.1', '2026-06-27 00:00:00+00',
 'Component', 'src/pages/LLNAssessmentPage.tsx', 'AI', 'requires_review', true,
 'audit_trail (abandonment event)', NULL, NULL,
 'ASQA: Complete evidence of assessment attempts', 'Abandonment events in audit trail',
 NULL, 'missing', ARRAY['audit', 'abandonment', 'quiz']),

('FEAT-017', 'Assessment Completion Handler', 'Assessment Engine', 'Automation',
 'Edge function triggered after assessment completion. Computes course recommendation, generates support plan, queues aXcelerate write-backs, triggers portfolio upload, sends admin notification email.',
 'Automate all post-assessment downstream actions as a single atomic workflow.',
 'implemented', 'critical', 'v0.1', '2026-06-27 00:00:00+00',
 'Edge Function', 'supabase/functions/on-assessment-complete/index.ts', 'AI', 'requires_review', true,
 'assessment_invitations (status update), support_plans, axcelerate_writeback_queue, email_queue',
 'Calls: generate-support-plan, upload-axcelerate-portfolio (indirectly)', NULL,
 NULL, 'Completion events, recommendation logged',
 'Service role key access', 'partial', ARRAY['assessment', 'completion', 'automation', 'edge-function']),

('FEAT-018', 'Student Landing Page', 'Assessment Engine', 'Student UI',
 'Token-gated student dashboard showing assigned assessments (LLN and/or Digital), status, due dates, and direct start links. Displays RTO branding.',
 'Give students a clear overview of their assessment requirements before beginning.',
 'implemented', 'high', 'v0.1', '2026-06-27 00:00:00+00',
 'Component', 'src/pages/StudentLandingPage.tsx', 'AI', 'requires_review', true,
 'assessment_invitations, invitation_assessments, assessments',
 NULL, 'StudentLandingPage — full responsive student dashboard',
 NULL, NULL, 'Token-scoped RLS',
 'partial', ARRAY['student', 'landing', 'portal']),

('FEAT-019', 'Assessment Version History', 'Assessment Engine', 'Audit',
 'Snapshots of assessments at each version change, stored for audit and rollback purposes.',
 'Ensure historical integrity of assessment content — critical for ASQA audit trail.',
 'implemented', 'medium', 'v0.1', '2026-06-27 00:00:00+00',
 'Migration', 'supabase/migrations/20260627014724_create_assessments_and_qualifications.sql', 'AI', 'requires_review', true,
 'assessment_version_history table', NULL, NULL,
 'ASQA: Version-controlled assessment evidence', 'Schema exists; UI integration unknown',
 NULL, 'missing', ARRAY['assessment', 'versioning', 'audit']),

('FEAT-020', 'Assessment Validation Workflow', 'Assessment Engine', 'Compliance',
 'Formal validation workflow for assessments: reviewer sign-off, industry consultation notes, validation status (validated/needs_revision), review due dates.',
 'Ensure assessments are formally validated as required by ASQA standards.',
 'implemented', 'high', 'v0.1', '2026-06-27 00:00:00+00',
 'Migration + Component', 'src/pages/ValidationPage.tsx', 'AI', 'requires_review', true,
 'assessment_validation table', NULL, 'ValidationPage',
 'ASQA: Assessment validation obligation', NULL, NULL,
 'partial', ARRAY['validation', 'compliance', 'asqa'])

ON CONFLICT (feature_id) DO NOTHING;
