/*
# EWO-014.11R2: Add package_hash column and update ES-001B standard

1. Schema Changes
   - Add `package_hash` column (text, nullable) to `ewo_engineering_packages`.
     This column stores a SHA-256 hash of the package body for future
     verification against archived Engineering Records.

2. Standard Update
   - Update ES-001B standard body to include the Engineering Record section
     requirement, lifecycle-aware Implementation Status, and actual engine
     name in the Implementation Engine field.

3. Security
   - No new tables created.
   - No RLS policy changes.
   - Column addition is non-destructive (nullable, no default needed).
*/

ALTER TABLE ewo_engineering_packages
  ADD COLUMN IF NOT EXISTS package_hash text;

UPDATE ecc_engineering_standards
SET
  body = 'Every completed Engineering Work Order shall return a complete Engineering Completion Package as a single copyable block. The package shall contain five sections in order: (1) Engineering Completion Report — full completion report with reference, title, status, deliverables, verification, and a Verification Evidence subsection summarising database migrations, edge function deployments, build results, TypeScript compilation, automated testing, runtime verification, deployment verification, and verification confidence. (2) Product Owner Testing — test checklist with expected results. The Implementation Engine shall NOT pre-populate test results. Each test shall present blank checkboxes: ☐ PASS and ☐ FAIL, plus a Comments field. The Product Owner is solely responsible for recording testing outcomes. The Implementation Engine may recommend expected results but shall never mark tests as passed. Acceptance criteria shall use unchecked checkboxes ([ ]). (3) Implementation Package — identifies the Implementation Engine (displaying the actual engine that performed the implementation, e.g. ATD, Claude Code, OpenAI GPT-5.5, Gemini, or future implementation engines — never a placeholder), Implementation Version, Implementation Date, Implementation Status (lifecycle-aware: Engineering Complete, Awaiting Product Owner Testing, Product Owner Accepted, Released, or Archived — reflecting the current engineering lifecycle state, never a fixed value), Next Engineering Work Order, a Next Engineering Work Order Summary (Reference, Title, Priority, Status), and the complete Implementation Prompt for the next work order. (4) Engineering Status — uses governed lifecycle fields: Implementation, Verification, Acceptance, Release, Learning, and Next Engineering. Each field shall reflect the actual engineering lifecycle stage. (5) Engineering Record — a final section before END OF PACKAGE containing: Engineering Record, Engineering Standard, Completion Package Version, Generated By, Implementation Engine, Generated On, Package ID (globally unique), Package Hash (SHA-256 hash uniquely identifying the generated package for future verification against archived Engineering Records), Record Status, and Archive Status. The entire package shall be produced as one copyable block so users press Copy once. No section may be returned separately. No additional engineering artefacts shall exist outside the package. The package shall not reference any specific implementation engine by name in its structure. The "Implementation Engine:" field identifies which engine consumed the work; changing engines requires changing only this field. Future implementation engines shall comply with this standard automatically.',
  updated_at = now()
WHERE version_introduced = 'ES-001B'
  AND title = 'ES-001B: Engineering Completion Package Standard';
