/*
# Create ecc_feature_documentation table

## Purpose
Stores rich per-feature documentation organised by doc_type. Each feature can have
multiple documentation entries (feature_overview, user_docs, technical_docs,
compliance_notes, change_log, ai_build_history). Entries are written by users or
auto-generated by AI.

## New Tables
- `ecc_feature_documentation`
  - `id` (uuid, primary key)
  - `feature_id` (text, NOT NULL) — references ecc_product_features.feature_id (not FK to avoid cascade issues)
  - `doc_type` (text) — 'feature_overview' | 'user_docs' | 'technical_docs' | 'compliance_notes' | 'change_log' | 'ai_build_history'
  - `title` (text)
  - `content` (text) — markdown body
  - `version` (text) — e.g. "1.0", "2.1"
  - `status` (text) — 'draft' | 'review' | 'approved' | 'archived'
  - `generated_by_ai` (boolean)
  - `ai_model` (text)
  - `author` (text)
  - `tags` (text[])
  - `metadata` (jsonb)
  - `created_at` (timestamptz)
  - `updated_at` (timestamptz)

## Security
- Enable RLS
- anon + authenticated can SELECT, INSERT, UPDATE, DELETE (single-tenant app, no row ownership)

## Notes
1. `feature_id` is a text code like 'ECC-001', matching ecc_product_features.feature_id
2. Multiple rows per feature_id + doc_type are allowed (versioned history)
3. `status` workflow: draft → review → approved → archived
4. `generated_by_ai` tracks AI-authored content
*/

CREATE TABLE IF NOT EXISTS ecc_feature_documentation (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  feature_id     text NOT NULL,
  doc_type       text NOT NULL DEFAULT 'feature_overview',
  title          text NOT NULL DEFAULT '',
  content        text NOT NULL DEFAULT '',
  version        text NOT NULL DEFAULT '1.0',
  status         text NOT NULL DEFAULT 'draft',
  generated_by_ai boolean NOT NULL DEFAULT false,
  ai_model       text,
  author         text,
  tags           text[] NOT NULL DEFAULT '{}',
  metadata       jsonb NOT NULL DEFAULT '{}',
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ecc_feature_docs_feature_id ON ecc_feature_documentation(feature_id);
CREATE INDEX IF NOT EXISTS idx_ecc_feature_docs_doc_type   ON ecc_feature_documentation(doc_type);
CREATE INDEX IF NOT EXISTS idx_ecc_feature_docs_status     ON ecc_feature_documentation(status);

ALTER TABLE ecc_feature_documentation ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_ecc_feature_docs"  ON ecc_feature_documentation;
DROP POLICY IF EXISTS "anon_insert_ecc_feature_docs"  ON ecc_feature_documentation;
DROP POLICY IF EXISTS "anon_update_ecc_feature_docs"  ON ecc_feature_documentation;
DROP POLICY IF EXISTS "anon_delete_ecc_feature_docs"  ON ecc_feature_documentation;

CREATE POLICY "anon_select_ecc_feature_docs" ON ecc_feature_documentation FOR SELECT
  TO anon, authenticated USING (true);

CREATE POLICY "anon_insert_ecc_feature_docs" ON ecc_feature_documentation FOR INSERT
  TO anon, authenticated WITH CHECK (true);

CREATE POLICY "anon_update_ecc_feature_docs" ON ecc_feature_documentation FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "anon_delete_ecc_feature_docs" ON ecc_feature_documentation FOR DELETE
  TO anon, authenticated USING (true);
